
```{r, echo=FALSE}
.libPaths(paste(getwd(), "/../libWin", sep = ""))
library(MASS)
library(SAE)
library(ggplot2)
library(microbenchmark)
```


```{r}
# in R
#######
rm(list=ls())
#beachte: Eingabe 'by row'

#pos-def matrix:
k   <- 2000
rho <- .3
S       <- matrix(rep(rho, k*k), nrow=k)
diag(S) <- 1
dat <- mvrnorm(10000, mu=rep(0,k), Sigma=S)
R <- cor(dat)
RR <- crossprod(R)

system.time(A <- solve(RR)%*% RR)
system.time(C <- chol2inv(chol(RR))%*%RR) 

# Inverse:
# Standard:
system.time(A <- solve(R))
# Was auch immer die Überlegung hierbei ist, es ist nicht schneller:
system.time(B <- qr.solve(R))
# Inverse für Cholesky-Decomposition scheint am schnellsten zu sein: (immer noch langsam)
system.time(C <- chol2inv(chol(R))) 




######################################
## In Schleifen:
######################################

#pos-def matrix: etwas kleiner!
k   <- 800
S       <- matrix(rep(rho, k*k), nrow=k)
diag(S) <- 1
dat <- mvrnorm(10000, mu=rep(0,k), Sigma=S)
R <- cor(dat)

invChol <- function(R, iter = 10) {
  system.time({
    Rfor <- list()
    for (i in 1:iter) {
      Rfor[[i]] <- chol2inv(chol(R), LINPACK = FALSE)
    }
  })
}

invSolve <- function(R, iter = 10) {
  system.time({
    Rfor <- list()
    for (i in 1:iter) {
      Rfor[[i]] <- solve(R)
    }
  })
}

iter = 100

# Keine überraschungen, die Berechnungszeit steigt linear:
invChol(R, iter)
invSolve(R, iter)

# Bringt hierbei anscheinen nichts.
library(compiler)
invCholCmp <- cmpfun(invChol)
invSolveCmp <- cmpfun(invSolve)

invCholCmp(R, iter)
invSolveCmp(R, iter)

######################################
## Vergleich mit RCppArmadillo:
######################################

# In Kombination mit matrixMultiplikation:
# berechne viel unsinn:
# (R'R)^-1 * (R'R)

k <- 1000
R <- matrix(rnorm(k^2), ncol = k)

#Vergleich: Mein möglichstes in R mit (meinen) Möglichkeiten in RCppArmadillo
#
benchInfos <- microbenchmark(
  #Nur zum Vergleich:
  solve(t(R) %*% R) %*% t(R) %*% R,
  {# Alles was ich bisher an Performance-Einsparungen (in R) lernen konnte:
    tmp1 <- crossprod(R)
    tmp2 <- chol2inv(chol(tmp1))
    tmp2 %*% tmp1
    }, 
  # Berechnung ohne spezielle Funktionen etc.
  cppArmFunc(R), 
  # Nutzt die Info, dass R'R positiv-definit ist
  cppArmFuncOpt(R), 
  # Rechnet intern die inverse mit der Cholesky-Decomposition - Die decomposition
  # ist implementiert, die Inverse dafür nicht.
  cppArmFuncChol(R))

benchInfos

```

```{r, fig.width = 20, fig.height=10}
autoplot(benchInfos)
```


```{r}
#Bester cpp gegen besten R-Code:
k <- 2000
R <- matrix(rnorm(k^2), ncol = k)

system.time({
  tmp1 <- crossprod(R)
  tmp2 <- chol2inv(chol(tmp1))
  tmp2 %*% tmp1
  })

system.time({
  cppArmFunc(R)
})

system.time({
  solve(t(R) %*% R) %*% t(R) %*% R
})

```

