# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppArmFunc <- function(X) {
    .Call('SAE_cppArmFunc', PACKAGE = 'SAE', X)
}

cppArmFuncOpt <- function(X) {
    .Call('SAE_cppArmFuncOpt', PACKAGE = 'SAE', X)
}

cppArmFuncPseudo <- function(X) {
    .Call('SAE_cppArmFuncPseudo', PACKAGE = 'SAE', X)
}

cppArmFuncChol <- function(X) {
    .Call('SAE_cppArmFuncChol', PACKAGE = 'SAE', X)
}

